name: build job

on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: '["self-hosted", "Linux", "X64"]'

jobs:
  build:
    runs-on: ${{ fromJSON(inputs.runner) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: pnpm build
