name: push workflow

on: push

jobs:
  install:
    uses: ./.github/workflows/jobs-install.yml

  lint:
    uses: ./.github/workflows/jobs-lint.yml

  build:
    uses: ./.github/workflows/jobs-build.yml
